language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
  - npm install -g gulp
  - mongo yoda --eval ''
  - gulp
script: gulp test
notifications:
  slack: siliconvalleybootcamp:5CgIMYv9koEBi2HTy7dWBiHv
